### ISSUE TITLE
ReadMe no longer instructs students to create a Bands component to render multiple Bands from

### ISSUE THREAD

**Issue by Sillhouette** [learn-co-curriculum/redux-delete-lab#17]
ReadMe no longer instructs students to create a Bands component to render multiple Bands from. Said instructions were removed from the readme a while back but the tests are still looking for that component to be created. Either we need to re-add the instructions for the component or we need to remove the tests that look at that component's functionality.

@maxwellbenton @rrcobb

**Comment by maxwellbenton** [comment]
Hey @Sillhouette,

I've added an additional step calling out the need for the `Bands` component and updated the step by step instructions, so this should be resolved now.

Thank you for spotting this and reporting!
