### ISSUE TITLE
Test are out of sync

### ISSUE THREAD

**Issue by Enoch2k2** [learn-co-curriculum/redux-delete-lab#2]
@aturkewi @Lukeghenco 
Test are out of sync - batch 000 (full stack with react)
https://github.com/learn-co-students/redux-delete-lab-v-000/blob/master/test/index-test.js

learn-co-curriculum
https://github.com/learn-co-curriculum/redux-delete-lab/blob/master/test/index-test.js

On line 94 of the test in the batch 000 it is passing text and id in the component as props, when in the lesson it states to pass in band={band} as props. They can pass it by reading the test. But it puts the lesson out of sync with the test.

**Comment by aturkewi** [comment]
Re-deployed and all set.
