### ISSUE TITLE
Bad Tests

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/redux-delete-lab#6]
The last couple tests only work if you are using 'this.props.band.id' in the dispatch function, but in the lesson before this, it has you passing the 'id' individually as a prop, and then passing 'this.props.id' into the dispatch function. Both function in browser the same way, but tests should reflect the way we are taught to do things.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials, restructured this lab contents and tests and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
