### ISSUE TITLE
Wrong Attribute: Line 29 in BandInput.js

### ISSUE THREAD

**Issue by kriti-rai** [learn-co-curriculum/redux-delete-lab#8]
It should be ...value = {this.state.bandName} not ...{this.state.text} as there's no such attribute in the state. This then allows automatic clearance of the input box every time a band name is submitted.

**Comment by maxwellbenton** [comment]
Hi @kriti-rai,

Thank you for spotting this and providing feedback. We've updated this lesson's starter code and replaced `this.state.text` with `this.state.bandName`, which should resolve this issue.

Thank you for contributing!
